### ISSUE TITLE
0.9-rc: 502 Bad Gateway

### ISSUE THREAD

**Issue by divadwong68** [urania-dev/snapp#91]
All I have to do is login and then do a refresh on the browser and 502 Bad Gateway error pops up.  Somehow it's saving some data that's causing this.  If I clear the data/cookie data, the error goes away.

**Comment by urania-dev** [comment]
Try env LOG_LEVEL=debug
It should log on the container logs

**Comment by urania-dev** [comment]
any news about this? happened again?

**Comment by divadwong68** [comment]
i added the LOG_LEVEL but it doesn't show anything.  If no one gets the 502 error, then I'll just chalk it up to my setup.  I know how to quick recover from it.

**Comment by urania-dev** [comment]
could it be that you had previous version cookie set at time of first launch? 

(Do you resolved with just that cleanup? it never happened again?)

**Comment by divadwong68** [comment]
no it still happens.  I checked my nginx proxy logs and found this. Don't know if it helps.
[13/Mar/2025:10:10:59 -0400] - 502 502 - GET https *redacted* "/dashboard/cm86ds3ng0003pp01sxsxnrmi" [Client *redacted*] [Length 556] [Gzip -] [Sent-to *redacted*] "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36" "-"

**Comment by urania-dev** [comment]
could you try to run docker image with env HOST=0.0.0.0

**Comment by urania-dev** [comment]
and since we are here: are you on arm  or amd64?

**Comment by divadwong68** [comment]
i'm on x64.  I'm not sure what you mean by HOST=0.0.0.0. I use docker compose.  I think you should just skip this and fix the app functionality issues first.

**Comment by urania-dev** [comment]
actually i'm rebuilding the image as we are talking, i already pushed fixes on github. that's why i'm focusing on this

in docker compose declare environments:
- HOST=0.0.0.0

like this (ignore version as it is not ended building yet)

![Image](https://github.com/user-attachments/assets/9da5deb1-16cd-4054-954f-a809b8553cf0)

**Comment by divadwong68** [comment]
After updating image to 0.9-rc-001 and adding HOST: 0.0.0.0 to my docker compose it didn't startup at all.  I looked at the docker logs and it looks like now it's requiring TOKEN_SECRET.  So I added that and the container started up, but unfortunately the behavior with the 502 Bad Gateway Errors remain the same. 

So are you saying this doesn't happen to anyone else?  I'd say don't bother fixing it then.  I don't feel like troubleshooting anymore.

**Comment by urania-dev** [comment]
tbf yours is only feed like this i received.

**Comment by urania-dev** [comment]
I'll close this for now, if you change your mind and wanted to give snapp another chance i'll be here :)

**Comment by matsicking** [comment]
I have the same issue in 0.9-rc-019
i added "HOST: 0.0.0.0" to my config but still the same problem, sadly also no logs with debug log level

**Comment by matsicking** [comment]
That peoblem also comes with the fact, that everything exept the homepage and /admin throw 502

**Comment by urania-dev** [comment]
Try remove host, Set Public URL equal to Origin, and put log_level=debug

If it doesnt show anything i can make a debug versione full of logs ad hoc for debugging this problem
:)

**Comment by urania-dev** [comment]
remove allowedHosted: HOST, and put allowedHost: true in 0.9-rc-020, so it should work.

**Comment by matsicking** [comment]
okaay, where should i put the "allowedHost: true"? I'm using Docker Compose

**Comment by urania-dev** [comment]
sorry, removed* i'm building 020 right now :)

**Comment by matsicking** [comment]
Okay, thx!

**Comment by urania-dev** [comment]
i'll wait for your test :)

**Comment by urania-dev** [comment]
Updated env file and readme to better understand which env is used where. so no more confusion hopefully :)

**Comment by ajshovon** [comment]
I was facing 502 bad gateway error. I am using nginx proxy manager for reverse proxy snapp. From nginx error log, i got this

Docker Image: `uraniadev/snapp:0.9-rc-020`

`2025/08/03 15:44:00 [error] 251#251: *4463 upstream sent too big header while reading response header from upstream, client: 100.10.10.10, server: example.com, request: "GET /auth/sign-in HTTP/2.0", upstream: "http://192.168.48.12:3000/auth/sign-in", host: "example.com"`

I added these on Custom Nginx Configuration and the issue was fixed

```
proxy_buffer_size          128k;
proxy_buffers              4 256k;
proxy_busy_buffers_size    256k;
```

Hope it solves if anyone facing similar issue

**Comment by urania-dev** [comment]
thank you for your submission, i'll look into this, and see if i can set a better image.
